DROP SCHEMA IF EXISTS TEST_TASK;
CREATE SCHEMA TEST_TASK;

CREATE TABLE IF NOT EXISTS TEST_TASK.RESTRICTED_WORD (
  id   INT PRIMARY KEY AUTO_INCREMENT,
  word VARCHAR(35) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TEST_TASK.COUNTRY (
  id           INT PRIMARY KEY AUTO_INCREMENT,
  country_code VARCHAR(5) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS TEST_TASK.QUESTION (
  id           INT PRIMARY KEY        AUTO_INCREMENT,
  content      VARCHAR(1000) NOT NULL,
  country_id   INT           NOT NULL,
  created_time TIMESTAMP     NOT NULL DEFAULT now(),
  FOREIGN KEY (country_id)
  REFERENCES TEST_TASK.COUNTRY (id)
);
